# Generated by Django 4.2.6 on 2023-11-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('items', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/package')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=250)),
                ('likes', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='static/images/course')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.package')),
            ],
        ),
    ]
