# Generated by Django 4.2.6 on 2023-11-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_packagetaken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='items',
        ),
    ]
