# Generated by Django 4.2.6 on 2023-11-09 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 11, 9, 17, 53, 14, 600808, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
