# Generated by Django 4.2.6 on 2023-10-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='static/images/profile_images'),
        ),
    ]
