# Generated by Django 4.2.6 on 2023-11-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_facebook_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[(0, 'Student'), (1, 'Instructor')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
