# Generated by Django 4.2.6 on 2023-11-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_course_id_alter_course_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
